log4j:
    appender:
        stdout: org.apache.log4j.ConsoleAppender
        stdout.layout: org.apache.log4j.PatternLayout
        stdout.layout.ConversionPattern: '%5p [%t] - %m'
    rootLogger: ERROR, stdout
logging:
    level:
        com:
            junyi:
                general:
                    dao: debug
mybatis:
    mapper-locations: classpath:mapper/*.xml
server:
    port: 1234
spring:
    datasource:
        password: 123456
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db_example?serverTimezone=UTC&characterEncoding=utf-8
        username: springuser
